# Generated by Django 3.2.9 on 2021-12-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20211209_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pswchdu', models.IntegerField(max_length=20)),
                ('group_name', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
