# Generated by Django 3.2.9 on 2021-12-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20211209_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_list',
            new_name='member',
        ),
    ]
