# Generated by Django 3.2.9 on 2021-12-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_user_list_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pswchdu',
            field=models.IntegerField(),
        ),
    ]
