# Generated by Django 3.2.9 on 2021-12-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20211209_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_member',
            name='pswd',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_member',
            name='u_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
