# Generated by Django 3.2.9 on 2022-01-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20211209_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='eqp_create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqp_name', models.CharField(max_length=30)),
                ('eqp_type', models.CharField(max_length=30)),
                ('param', models.CharField(max_length=30)),
                ('sensors', models.IntegerField()),
                ('log_inv', models.IntegerField()),
                ('ip_addr', models.IntegerField()),
                ('mach_code', models.IntegerField()),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
    ]
