# Generated by Django 3.2.9 on 2022-01-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_eqp_create'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eqp_create',
            new_name='eqp_list',
        ),
    ]
