# Generated by Django 3.2.9 on 2022-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_rename_eqp_create_eqp_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqp_list',
            name='ip_addr',
            field=models.CharField(max_length=50),
        ),
    ]
