# Generated by Django 3.2.9 on 2022-01-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_eqp_list_ip_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqp_list',
            name='eqp_status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
