# Generated by Django 3.2.9 on 2022-01-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_eqp_list_eqp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqp_list',
            name='eqp_status',
            field=models.CharField(default='InActive', max_length=30),
        ),
    ]
