# Generated by Django 3.2.9 on 2022-01-14 13:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_eqp_list_eqp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='eqp_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=50)),
                ('conn_status', models.BooleanField()),
                ('data', models.CharField(max_length=200)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
