# Generated by Django 3.2.9 on 2022-01-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_auto_20220117_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqp_data',
            name='eqp_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
