# Generated by Django 3.2.9 on 2022-02-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_admin_group_operator_group_supervise_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_group',
        ),
    ]
